language: java

jdk:
  - openjdk11

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "dyuusxtwkeCE4dpCZpUbeqzjdGHB7m7zKZyUC3T06eipA7prgbJlfoiFrF2jb4ZXg/FXZLuR8Nuj2sCnOpBRzN7RTdWaSaN+uI+PvMV/Fg63pvrPaXxEhK3gJVvls7tUYb9nePgVoTaV3/s9pX7nNAdCcoz5p1HNzkznWu8WFhk="
    - secure: "IrKV2XW06zepGHFJ0bwUbBMTLnf1U5emXhSzuBPzcFLnWWTkxm3oCcCnmf5Lhwa7QVKOL51Xqmg1cKlCQwU7MepT5zh51Fd8TI5NASpX2DA93szOWoWlLxoO/YT68INneaIrXhDxztADF3f5teQ83Nnx2g4V12YX5ZJbbN2b3E0="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false
