name: build

on:
  pull_request: {}
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - run: mvn verify source:jar javadoc:jar

      - name: Upload snapshot
        if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'JakeWharton/twirl-maven-plugin' }}
        run: mvn clean source:jar javadoc:jar deploy --settings=".github/workflows/settings.xml" -Dmaven.test.skip=true
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
